Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

# MySQL Exercise 1: Welcome to your first notebook!

Database interfaces vary greatly across platforms and companies.  The interface you will be using here, called Jupyter, is a web application designed for data science teams who need to create and share documents that share live code.  We will be taking advantage of Jupyter's ability to integrate instructional text with areas that allow you to write and run SQL queries.  In this course, you will practice writing queries about the Dognition data set in these Jupyter notebooks as I give you step-by-step instructions through written text.  Then once you are comfortable with the query syntax, you will practice writing queries about the Dillard's data set in Teradata Viewpoint's more traditional SQL interface, called SQL scratchpad. Your assessments each week will be based on the exercises you complete using the Dillard's dataset.

Jupyter runs in a language called Python, so some of the commands you will run in these MySQL exercises will require incorporating small amounts of Python code, along with the MySQL query itself.  Python is a very popular programming language with many statistical and visualization libraries, so you will likely encounter it in other business analysis settings.  Since many data analysis projects do not use Python, however, I will point out to you what parts of the commands are specific to Python interfaces. 

## The first thing you should do every time you start working with a database: load the SQL library

Since Jupyter is run through Python, the first thing you need to do to start practicing SQL queries is load the SQL library.  To do this, type the following line of code into the empty cell below:

```python
%load_ext sql
```

In [1]:
%load_ext sql


The "%" in this line of code is syntax for Python, not SQL.  The "cell" I am referring to is the empty box area beside the "In [  ]:" you see on the left side of the screen.

Once you've entered the line of code, press the "run" button on the Jupyter toolbar that looks like an arrow.  It's located under “cell” in the drop-down menu bar, and next to the stop button (the solid square).  The run button is outlined in red in this picture:

![alt text](https://duke.box.com/shared/static/u9chww13kim30t5p6ndh404d9ap6auwf.jpg)

**TIP: Whenever instructions say “run” or "execute" a command in future exercises, type the appropriate code into the empty cell and execute it by pressing this same button with the arrow.**

When the library has loaded, you will see a number between the brackets that preceed the line of code you executed: 

For example, it might look like this: 

```
In [2]:
```
    

## The second thing you must do every time you want to start working with a database: connect to the database you need to use.

Now that the SQL library is loaded, we need to connect to a database.  The following command will log you into the MySQL server at localhost as the user 'studentuser' and will select the database named 'dognitiondb' :

```python
mysql://studentuser:studentpw@localhost/dognitiondb
```

However, to execute this command using SQL language instead of Python, you will need to begin the line of code with:

```python
%sql
```

Thus, the complete line of code is:

```python
%sql mysql://studentuser:studentpw@localhost/dognitiondb
```

Connect to the database by typing this command into the cell below, and running it (note: you can copy and paste the command from above rather than typing it, if you choose):

In [2]:
%sql mysql://studentuser:studentpw@localhost/dognitiondb

<mark>***Every time you run a line of SQL code in Jupyter, you will need to preface the line with "%sql".  Remember to do this, even though I will not explicitly instruct you to do so for the rest of the exercises in this course.***</mark>

Once you are connected, the output cell (which reads "Out" followed by brackets) will read: "Connected:studentuser@dognitiondb".  To make this the default database for our queries, run this "USE" command:

```python
%sql USE dognitiondb
```

In [3]:
%sql USE dognitiondb

 * mysql://studentuser:***@localhost/dognitiondb
0 rows affected.

[]

You are now ready to run queries in the Dognition database!


## The third thing you should do every time you start working with a new database: get to know your data

The data sets you will be working with in business settings will be big.  REALLY big.  If you just start making queries without knowing what you are pulling out, you could hang up your servers or be staring at your computer for hours before you get an output.  Therefore, even if you are given an ER diagram or relational schema like we learned about in the first week of the course, before you start querying I strongly recommend that you (1) confirm how many tables each database has, and (2) identify the fields contained in each table of the database.  To determine how many tables each database has, use the SHOW command:

```mySQL
SHOW tables
```

**Try it yourself (TIP: if you get an error message, it's probably because you forgot to start the query with "%sql"):**

In [4]:
%sql SHOW tables

 * mysql://studentuser:***@localhost/dognitiondb
6 rows affected.

[('complete_tests',),
 ('dogs',),
 ('exam_answers',),
 ('reviews',),
 ('site_activities',),
 ('users',)]

The output that appears above should show you there are six tables in the Dognition database.  To determine what columns or fields (we will use those terms interchangeably in this course) are in each table, you can use the SHOW command again, but this time (1) you have to clarify that you want to see columns instead of tables, and (2) you have to specify from which table you want to examine the columns. 

The syntax, which sounds very similar to what you would actually say in the spoken English language, looks like this:

```mySQL
SHOW columns FROM (enter table name here)
```
or if you have multiple databases loaded:
```mySQL
SHOW columns FROM (enter table name here) FROM (enter database name here)
```
or
```mySQL
SHOW columns FROM databasename.tablename 
```
<mark> Whenever you have multiple databases loaded, you will need to specify which database a table comes from using one of the syntax options described above.</mark>

As I said in the earlier "Introduction to Query Syntax" video, it makes it easier to read and troubleshoot your queries if you always write SQL keywords in UPPERCASE format and write your table and field names in their native format.  We will only use the most important SQL keywords in this course, but a full list can be found here:

https://dev.mysql.com/doc/refman/5.7/en/keywords.html


**Question 1: How many columns does the "dogs" table have?  Enter the appropriate query below to find out:**

In [14]:
%sql SHOW columns FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
21 rows affected.

[('gender', 'varchar(255)', 'YES', '', None, ''),
 ('birthday', 'varchar(255)', 'YES', '', None, ''),
 ('breed', 'varchar(255)', 'YES', '', None, ''),
 ('weight', 'int(11)', 'YES', '', None, ''),
 ('dog_fixed', 'tinyint(1)', 'YES', '', None, ''),
 ('dna_tested', 'tinyint(1)', 'YES', '', None, ''),
 ('created_at', 'datetime', 'NO', '', None, ''),
 ('updated_at', 'datetime', 'NO', '', None, ''),
 ('dimension', 'varchar(255)', 'YES', '', None, ''),
 ('exclude', 'tinyint(1)', 'YES', '', None, ''),
 ('breed_type', 'varchar(255)', 'YES', '', None, ''),
 ('breed_group', 'varchar(255)', 'YES', '', None, ''),
 ('dog_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('user_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('total_tests_completed', 'varchar(255)', 'YES', '', None, ''),
 ('mean_iti_days', 'varchar(255)', 'YES', '', None, ''),
 ('mean_iti_minutes', 'varchar(255)', 'YES', '', None, ''),
 ('median_iti_days', 'varchar(255)', 'YES', '', None, ''),
 ('median_iti_minutes', 'varchar(255)', 'YES', '', None, ''),
 ('time_diff_between_first_and_last_game_days', 'varchar(255)', 'YES', '', None, ''),
 ('time_diff_between_first_and_last_game_minutes', 'varchar(255)', 'YES', '', None, '')]

You should have determined that the "dogs" table has 21 columns.  

An alternate way to learn the same information would be to use the DESCRIBE function.  The syntax is:

```mySQL
DESCRIBE tablename
```

**Question 2: Try using the DESCRIBE function to learn how many columns are in the "reviews" table:**

In [15]:
%sql DESC reviews

 * mysql://studentuser:***@localhost/dognitiondb
7 rows affected.

[('rating', 'int(11)', 'YES', '', None, ''),
 ('created_at', 'datetime', 'NO', '', None, ''),
 ('updated_at', 'datetime', 'NO', '', None, ''),
 ('user_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('dog_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('subcategory_name', 'varchar(60)', 'YES', '', None, ''),
 ('test_name', 'varchar(60)', 'YES', '', None, '')]

You should have determined that there are 7 columns in the "reviews" table.  

The SHOW and DESCRIBE functions give a lot more information about the table than just how many columns, or fields, there are.  Indeed, the first column of the output shows the title of each field in the table.  The column next to that describes what type of data are stored in that column.  There are 3 main types of data in MySQL: text, number, and datetime.  There are many subtypes of data within these three general categories, as described here:

https://www.hostgator.com/help/article/mysql-variable-types

The next column in the SHOW/DESCRIBE output indicates whether null values can be stored in the field in the table.  The "Key" column of the output provides the following information about each field of data in the table being described (see https://dev.mysql.com/doc/refman/5.7/en/show-columns.html for more information):

+ Empty: the column either is not indexed or is indexed only as a secondary column in a multiple-column, nonunique index.
+ PRI: the column is a PRIMARY KEY or is one of the columns in a multiple-column PRIMARY KEY.
+ UNI: the column is the first column of a UNIQUE index. 
+ MUL: the column is the first column of a nonunique index in which multiple occurrences of a given value are permitted within the column.

The "Default" field of the output indicates the default value that is assigned to the field. The "Extra" field contains any additional information that is available about a given field in that table. 

**Questions 3-6: In the cells below, examine the fields in the other 4 tables of the Dognition database:**

In [16]:
%sql DESC complete_tests

 * mysql://studentuser:***@localhost/dognitiondb
6 rows affected.

[('created_at', 'datetime', 'NO', '', None, ''),
 ('updated_at', 'datetime', 'NO', '', None, ''),
 ('user_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('dog_guid', 'varchar(60)', 'YES', 'MUL', None, ''),
 ('test_name', 'varchar(60)', 'YES', '', None, ''),
 ('subcategory_name', 'varchar(60)', 'YES', '', None, '')]

In [17]:
%sql DESC users

 * mysql://studentuser:***@localhost/dognitiondb
16 rows affected.

[('sign_in_count', 'int(11)', 'YES', '', '0', ''),
 ('created_at', 'datetime', 'NO', '', None, ''),
 ('updated_at', 'datetime', 'NO', '', None, ''),
 ('max_dogs', 'int(11)', 'YES', '', '0', ''),
 ('membership_id', 'int(11)', 'YES', '', None, ''),
 ('subscribed', 'tinyint(1)', 'YES', '', '0', ''),
 ('exclude', 'tinyint(1)', 'YES', '', None, ''),
 ('free_start_user', 'tinyint(1)', 'YES', '', None, ''),
 ('last_active_at', 'datetime', 'YES', '', None, ''),
 ('membership_type', 'int(11)', 'YES', '', None, ''),
 ('user_guid', 'text', 'YES', 'MUL', None, ''),
 ('city', 'varchar(255)', 'YES', '', None, ''),
 ('state', 'varchar(255)', 'YES', '', None, ''),
 ('zip', 'varchar(255)', 'YES', '', None, ''),
 ('country', 'varchar(255)', 'YES', '', None, ''),
 ('utc_correction', 'varchar(255)', 'YES', '', None, '')]

In [18]:
%sql DESC exam_answers

 * mysql://studentuser:***@localhost/dognitiondb
8 rows affected.

[('script_detail_id', 'int(11)', 'YES', '', None, ''),
 ('subcategory_name', 'varchar(255)', 'YES', '', None, ''),
 ('test_name', 'varchar(255)', 'YES', '', None, ''),
 ('step_type', 'varchar(255)', 'YES', '', None, ''),
 ('start_time', 'datetime', 'YES', '', None, ''),
 ('end_time', 'datetime', 'YES', '', None, ''),
 ('loop_number', 'int(11)', 'YES', '', None, ''),
 ('dog_guid', 'varchar(60)', 'YES', '', None, '')]

In [19]:
%sql DESC site_activities

 * mysql://studentuser:***@localhost/dognitiondb
11 rows affected.

[('activity_type', 'varchar(150)', 'YES', 'MUL', None, ''),
 ('description', 'text', 'YES', '', None, ''),
 ('membership_id', 'int(11)', 'YES', '', None, ''),
 ('category_id', 'int(11)', 'YES', '', None, ''),
 ('script_id', 'int(11)', 'YES', '', None, ''),
 ('created_at', 'datetime', 'NO', '', None, ''),
 ('updated_at', 'datetime', 'NO', '', None, ''),
 ('user_guid', 'varchar(255)', 'YES', 'MUL', None, ''),
 ('script_detail_id', 'int(11)', 'YES', '', None, ''),
 ('test_name', 'varchar(255)', 'YES', '', None, ''),
 ('dog_guid', 'varchar(255)', 'YES', 'MUL', None, '')]

As you examine the fields in each table, you will notice that none of the Dognition tables have primary keys declared.  However, take note of which fields say "MUL" in the "Key" column of the DESCRIBE output, because these columns can still be used to link tables together.  An important thing to keep in mind, though, is that because these linking columns were not configured as primary keys, it is possible the linking fields contain NULL values or duplicate rows.
    
If you do not have a ER diagram or relational schema of the Dognition database yet, consider making one at this point, because you will need to refer back to table and column names constantly throughout designing your queries  (if you don't remember what primary keys, secondary keys, ER diagrams, or relational schemas are, review the material discussed in the first week of this course).  Some database interfaces do provide notes or visual representations about the information in each table for easy reference, but since the Jupyter interface does not provide this, take your own notes and make your own diagrams, and keep them handy.  As you will see, these diagrams and notes will save you a lot of time when you design your queries to pull data.


## Using SELECT to look at your raw data

Once you have an idea of what is in your tables look like and how they might interact, it's a good idea to look at some of the raw data itself so that you are aware of any anomalies that could pose problems for your analysis or interpretations.  To do that, we will use arguably the most important SQL statement for analysts: the SELECT statement.

SELECT is used anytime you want to retrieve data from a table.  In order to retrieve that data, you always have to provide at least two pieces of information: 
   
    (1) what you want to select, and      
    (2) from where you want to select it.  
    
I recommend that you always format your SQL code to ensure that these two pieces of information are on separate lines, so they are easy to identify quickly by eye.  

The skeleton of a SELECT statement looks like this:

```mySQL
SELECT
FROM
```

To fill in the statement, you indicate the column names you are interested in after "SELECT" and the table name (and database name, if you have multiple databases loaded) you are drawing the information from after "FROM."  So in order to look at the breeds in the dogs table, you would execute the following command:

```mySQL
SELECT breed
FROM dogs;
```

Remember:
+ SQL syntax and keywords are case insensitive.  I recommend that you always enter SQL keywords in upper case and table or column names in either lower case or their native format to make it easy to read and troubleshoot your code, but it is not a requirement to do so.  Table or column names are often case insensitive as well, but defaults may vary across database platforms so it's always a good idea to check.
+ Table or column names with spaces in them need to be surrounded by quotation marks in SQL.  MySQL accepts both double and single quotation marks, but some database systems only accept single quotation marks.  In all database systems, if a table or column name contains an SQL keyword, the name must be enclosed in backticks instead of quotation marks.
> ` 'the marks that surrounds this phrase are single quotation marks' `     
> ` "the marks that surrounds this phrase are double quotation marks" `     
> `` `the marks that surround this phrase are backticks` ``
+ The semi-colon at the end of a query is only required when you have multiple separate queries saved in the same text file or editor.  That said, I recommend that you make it a habit to always include a semi-colon at the end of your queries.  

<mark>An important note for executing queries in Jupyter: in order to tell Python that you want to execute SQL language on multiple lines, you must include two percent signs in front of the SQL prefix instead of one.</mark>  Therefore, to execute the above query, you should enter:

```mySQL
%%sql
SELECT breed
FROM dogs;
```

When Jupyter is busy executing a query, you will see an asterisk in the brackets next to the output field:

```
Out [*]
```

When the query is completed, you will see a number in the brackets next to the output field.

```
Out [5]
```

**Try it yourself:**

In [21]:
%%sql
SELECT breed 
FROM dogs
LIMIT 5;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.

[('Labrador Retriever',),
 ('Shetland Sheepdog',),
 ('Golden Retriever',),
 ('Golden Retriever',),
 ('Shih Tzu',)]

When you do so, you will see a line at the top of the output panel that says "35050 rows affected".  This means that there are 35050 rows of data in the dogs table.  Each row of the output lists the name of the breed of the dog represented by that entry.  Notice that some breed names are listed multiple times, because several dogs of that breed have participated in the Dognition tests.

If you scroll all the way down to the bottom of the output, you will see a notification that says "35050 rows, truncated to displaylimit of 1000."  We have set up a display limit of 1000 rows in these notebooks to ensure that our database servers are not overloaded, and to reduce the amount of time you have to wait for the query output. However, in a actual scenario these limits would not necessarily be in place for you.  Therefore, before we go any further, I want to show you how you could restrict the number of rows outputted by a query.

![Alt text](https://duke.box.com/shared/static/dm85qcbpdsza8tc7be8x7tc6x6tr2xjq.jpg)



## Using LIMIT to restrict the number of rows in your output (and prevent system crashes)

The MySQL clause you should use is called LIMIT, and it is always placed at the very end of your query.  The simplest version of a limit statement looks like this:

```mySQL
SELECT breed
FROM dogs LIMIT 5;
```

The "5" in this case indicates that you will only see the first 5 rows of data you select.  

**Question 7: In the next cell, try entering a query that will let you see the first 10 rows of the breed column in the dogs table.**

In [24]:
%%sql
SELECT breed
FROM dogs
LIMIT 5;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.

[('Labrador Retriever',),
 ('Shetland Sheepdog',),
 ('Golden Retriever',),
 ('Golden Retriever',),
 ('Shih Tzu',)]

You can also select rows of data from different parts of the output table, rather than always just starting at the beginning.  To do this, use the OFFSET clause after LIMIT. The number after the OFFSET clause indicates from which row the output will begin querying.  Note that the offset of Row 1 of a table is actually 0.  Therefore, in the following query:

```mySQL
SELECT breed
FROM dogs LIMIT 10 OFFSET 5;
```

10 rows of data will be returned, starting at Row 6.  

An alternative way to write the OFFSET clause in the query is:

```mySQL
SELECT breed
FROM dogs LIMIT 5, 10;
```

In this notation, the offset is the number before the comma, and the number of rows returned is the number after the comma.  

**Try it yourself:**

In [25]:
%%sql
SELECT breed 
FROM dogs
LIMIT 5,10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[('Siberian Husky',),
 ('Shih Tzu',),
 ('Mixed',),
 ('Labrador Retriever',),
 ('Shih Tzu-Poodle Mix',),
 ('German Shepherd Dog-Pembroke Welsh Corgi Mix',),
 ('Vizsla',),
 ('Pug',),
 ('Boxer',),
 ('German Shepherd Dog-Nova Scotia Duck Tolling Retriever Mix',)]

The LIMIT command is one of the pieces of syntax that can vary across database platforms.  MySQL uses LIMIT to restrict the output, but other databases including Teradata use a statement called "TOP" instead.  Oracle has yet another syntax:

http://www.tutorialspoint.com/sql/sql-top-clause.htm

Make sure to look up the correct syntax for the database type you are using.


## Using SELECT to query multiple columns

Now that we know how to limit our output, we are ready to make our SELECT statement work a little harder.  The SELECT statement can be used to select multiple columns as well as a single column.  The output of the query will depend on the order of the columns you enter after the SELECT statement in your query.  <mark> When you enter column names, separate each name with a comma, but do NOT include a comma after the last column name. </mark>

**Try the following query with different orders of the column names to observe the differences in output (I will include a LIMIT statement in many of the examples I use in the rest of the course, but feel free to change or remove them to explore different aspects of the data):**

```mySQL
SELECT breed, breed_type, breed_group
FROM dogs LIMIT 5, 10;
```

In [26]:
%%sql
SELECT breed, breed_type, breed_group
FROM dogs
LIMIT 5,10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[('Siberian Husky', 'Pure Breed', 'Working'),
 ('Shih Tzu', 'Pure Breed', 'Toy'),
 ('Mixed', "Mixed Breed/ Other/ I Don't Know", None),
 ('Labrador Retriever', 'Pure Breed', 'Sporting'),
 ('Shih Tzu-Poodle Mix', 'Cross Breed', None),
 ('German Shepherd Dog-Pembroke Welsh Corgi Mix', 'Cross Breed', None),
 ('Vizsla', 'Pure Breed', 'Sporting'),
 ('Pug', 'Pure Breed', 'Toy'),
 ('Boxer', 'Pure Breed', 'Working'),
 ('German Shepherd Dog-Nova Scotia Duck Tolling Retriever Mix', 'Cross Breed', None)]

Another trick to know about when using SELECT is that <mark> you can use an asterisk as a "wild card" to return all the data in a table.</mark>  (A wild card is defined as a character that will represent or match any character or sequence of characters in a query.) <mark> Take note, this is very risky to do if you do not limit your output or if you don't know how many data are in your database, so use the wild card with caution.</mark>  However, it is a handy tool to use when you don't have all the column names easily available or when you know you want to query an entire table.  

The syntax is as follows:

```mySQL
SELECT *
FROM dogs LIMIT 5, 10;
```

**Question 8: Try using the wild card to query the reviews table:**

In [27]:
%%sql SELECT * 
FROM dogs 
LIMIT 5,10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[('male', '2011', 'Siberian Husky', 60, 1, 0, datetime.datetime(2013, 2, 5, 18, 14, 14), datetime.datetime(2013, 7, 25, 19, 41, 49), 'stargazer', None, 'Pure Breed', 'Working', 'fd27b948-7144-11e5-ba71-058fbc01cf0b', 'ce13615c-7144-11e5-ba71-058fbc01cf0b', '20', '0.1785873538', '257.16578947', '0.0035648148035', '5.1333333171', '3.3931597222', '4886.15'),
 ('male', '1982', 'Shih Tzu', 190, 1, 0, datetime.datetime(2013, 2, 5, 18, 16, 24), datetime.datetime(2014, 5, 30, 15, 52, 54), 'maverick', 1, 'Pure Breed', 'Toy', 'fd27ba1a-7144-11e5-ba71-058fbc01cf0b', 'ce135e14-7144-11e5-ba71-058fbc01cf0b', '27', '6.1905898326', '8914.449359', '0.00033564807185', '0.48333322347', '160.95533565', '231775.68333'),
 ('male', '2012', 'Mixed', 50, 1, 0, datetime.datetime(2013, 2, 5, 18, 44, 2), datetime.datetime(2013, 7, 25, 19, 41, 49), 'protodog', None, "Mixed Breed/ Other/ I Don't Know", None, 'fd27bbbe-7144-11e5-ba71-058fbc01cf0b', 'ce135f2c-7144-11e5-ba71-058fbc01cf0b', '20', '0.0080750487303', '11.628070172', '0.0046412037941', '6.6833334635', '0.15342592588', '220.93333326'),
 ('male', '2008', 'Labrador Retriever', 70, 1, 0, datetime.datetime(2013, 2, 5, 20, 59, 42), datetime.datetime(2013, 7, 25, 19, 41, 49), 'einstein', None, 'Pure Breed', 'Sporting', 'fd27c1c2-7144-11e5-ba71-058fbc01cf0b', 'ce136a1c-7144-11e5-ba71-058fbc01cf0b', '20', '0.68410453216', '985.11052631', '0.0033796295731', '4.8666665853', '12.997986111', '18717.1'),
 ('male', '2008', 'Shih Tzu-Poodle Mix', 0, 1, 0, datetime.datetime(2013, 2, 5, 21, 30, 14), datetime.datetime(2013, 7, 25, 19, 41, 49), 'socialite', None, 'Cross Breed', None, 'fd27c5be-7144-11e5-ba71-058fbc01cf0b', 'ce136ac6-7144-11e5-ba71-058fbc01cf0b', '20', '0.22328155458', '321.5254386', '0.0038888889878', '5.6000001424', '4.2423495371', '6108.9833334'),
 ('female', '2011', 'German Shepherd Dog-Pembroke Welsh Corgi Mix', 40, 1, 0, datetime.datetime(2013, 2, 5, 22, 29, 24), datetime.datetime(2013, 7, 25, 19, 41, 49), None, None, 'Cross Breed', None, 'fd27c74e-7144-11e5-ba71-058fbc01cf0b', 'ce136c24-7144-11e5-ba71-058fbc01cf0b', '14', '25.69619391', '37002.519231', '0.0058449073678', '8.4166666097', '334.05052083', '481032.75'),
 ('male', '2011', 'Vizsla', 60, 1, 0, datetime.datetime(2013, 2, 5, 23, 9, 37), datetime.datetime(2013, 7, 25, 19, 41, 49), 'socialite', None, 'Pure Breed', 'Sporting', 'fd27c7d0-7144-11e5-ba71-058fbc01cf0b', 'ce136e36-7144-11e5-ba71-058fbc01cf0b', '20', '0.0053776803082', '7.7438596438', '0.0044791667034', '6.4500000529', '0.10217592586', '147.13333323'),
 ('female', '2007', 'Pug', 20, 1, 0, datetime.datetime(2013, 2, 5, 23, 10, 40), datetime.datetime(2013, 7, 31, 21, 57, 21), 'stargazer', None, 'Pure Breed', 'Toy', 'fd27c852-7144-11e5-ba71-058fbc01cf0b', 'ce136ee0-7144-11e5-ba71-058fbc01cf0b', '20', '0.051511939572', '74.177192984', '0.0039930555499', '5.7499999919', '0.97872685187', '1409.3666667'),
 ('female', '2010', 'Boxer', 50, 1, 0, datetime.datetime(2013, 2, 5, 23, 27, 59), datetime.datetime(2013, 7, 25, 19, 41, 49), 'ace', None, 'Pure Breed', 'Working', 'fd27c8d4-7144-11e5-ba71-058fbc01cf0b', 'ce136f94-7144-11e5-ba71-058fbc01cf0b', '20', '0.15856725147', '228.33684211', '0.0039351851456', '5.6666666097', '3.0127777779', '4338.4000001'),
 ('male', '2010', 'German Shepherd Dog-Nova Scotia Duck Tolling Retriever Mix', 30, 1, 0, datetime.datetime(2013, 2, 6, 0, 9, 33), datetime.datetime(2014, 5, 30, 15, 52, 56), None, None, 'Cross Breed', None, 'fd27c956-7144-11e5-ba71-058fbc01cf0b', 'ce134be0-7144-11e5-ba71-058fbc01cf0b', '11', '2.8247997685', '4067.7116667', '0.0037731481142', '5.4333332845', '28.247997685', '40677.116667')]

NOTE: if you do this for the dogs table, your output will be too wide to see at one time in the dialog box.  Use the scroll bars at bottom and to the right of the dialog box to see the entire output table.  
   
     
SELECT statements can also be used to make new derivations of individual columns using "+" for addition, "-" for subtraction, "\*" for multiplication, or "/" for division.  For example, if you wanted the median inter-test intervals in hours instead of minutes or days, you could query:

```mySQL
SELECT median_iti_minutes / 60
FROM dogs LIMIT 5, 10;
```

**Question 9: Go ahead and try it, adding in a column to your output that shows you the original median_iti in minutes.**

In [29]:
%%sql
SELECT mean_iti_minutes/60 
FROM dogs
LIMIT 5,10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[(4.286096491166666,),
 (148.57415598333333,),
 (0.19380116953333332,),
 (16.418508771833334,),
 (5.35875731,),
 (616.70865385,),
 (0.12906432739666665,),
 (1.2362865497333333,),
 (3.8056140351666667,),
 (67.795194445,)]

## Now it's time to practice writing your own SELECT statements.  

**Question 10: How would you retrieve the first 15 rows of data from the dog_guid, subcategory_name, and test_name fields of the Reviews table, in that order?**

In [35]:
%%sql
SELECT dog_guid, subcategory_name, test_name
FROM reviews
LIMIT 15;

 * mysql://studentuser:***@localhost/dognitiondb
15 rows affected.

[('ce3ac77e-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Yawn Warm-up'),
 ('ce2aedcc-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Eye Contact Warm-up'),
 ('ce2aedcc-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Eye Contact Game'),
 ('ce2aedcc-7144-11e5-ba71-058fbc01cf0b', 'Communication', 'Treat Warm-up'),
 ('ce405c52-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Yawn Warm-up'),
 ('ce405c52-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Yawn Game'),
 ('ce405c52-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Eye Contact Game'),
 ('ce405e28-7144-11e5-ba71-058fbc01cf0b', 'Communication', 'Treat Warm-up'),
 ('ce405e28-7144-11e5-ba71-058fbc01cf0b', 'Cunning', 'Turn Your Back'),
 ('ce2609c4-7144-11e5-ba71-058fbc01cf0b', 'Communication', 'Treat Warm-up'),
 ('ce2609c4-7144-11e5-ba71-058fbc01cf0b', 'Communication', 'Arm Pointing'),
 ('ce2609c4-7144-11e5-ba71-058fbc01cf0b', 'Communication', 'Foot Pointing'),
 ('ce260c1c-7144-11e5-ba71-058fbc01cf0b', 'Shaker Game', 'Shaker Warm-Up'),
 ('ce3fd48a-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Yawn Game'),
 ('ce3fd48a-7144-11e5-ba71-058fbc01cf0b', 'Empathy', 'Eye Contact Warm-up')]

**Question 11: How would you retrieve 10 rows of data from the activity_type, created_at, and updated_at fields of the site_activities table, starting at row 50?  What do you notice about the created_at and updated_at fields?**

In [37]:
%%sql
SELECT activity_type, created_at, updated_at
FROM site_activities
LIMIT 10;

 * mysql://studentuser:***@localhost/dognitiondb
10 rows affected.

[('point_in_cat', datetime.datetime(2013, 7, 25, 19, 36, 18), datetime.datetime(2013, 7, 25, 19, 36, 18)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 1), datetime.datetime(2013, 7, 25, 19, 39, 1)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 17), datetime.datetime(2013, 7, 25, 19, 39, 17)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 23), datetime.datetime(2013, 7, 25, 19, 39, 23)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 33), datetime.datetime(2013, 7, 25, 19, 39, 33)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 31), datetime.datetime(2013, 7, 25, 19, 39, 31)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 38), datetime.datetime(2013, 7, 25, 19, 39, 38)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 39, 46), datetime.datetime(2013, 7, 25, 19, 39, 46)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 41, 43), datetime.datetime(2013, 7, 25, 19, 41, 43)),
 ('point_in_cat', datetime.datetime(2013, 7, 25, 19, 41, 53), datetime.datetime(2013, 7, 25, 19, 41, 53))]

**Question 12: How would you retrieve 20 rows of data from all the columns in the users table, starting from row 2000?  What do you notice about the free_start_user field?**

In [39]:
%%sql
SELECT * FROM users
LIMIT 20, 2000;

 * mysql://studentuser:***@localhost/dognitiondb
2000 rows affected.

[(3, datetime.datetime(2013, 2, 6, 2, 34, 46), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce1375b6-7144-11e5-ba71-058fbc01cf0b', 'Grayslake', 'IL', '60030', 'US', '-6'),
 (9, datetime.datetime(2013, 2, 6, 3, 37, 7), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, None, 2, 'ce1377b4-7144-11e5-ba71-058fbc01cf0b', 'Falls Church', 'VA', '22044', 'US', '-5'),
 (22, datetime.datetime(2013, 2, 6, 3, 32, 8), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 7, 30, 21, 54, 31), 2, 'ce137700-7144-11e5-ba71-058fbc01cf0b', 'Everett', 'WA', '98203', 'US', '-8'),
 (5, datetime.datetime(2013, 2, 6, 4, 54, 49), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 9, 20, 17, 8, 44), 2, 'ce137868-7144-11e5-ba71-058fbc01cf0b', 'Dixon', 'CA', '95620', 'US', '-8'),
 (5, datetime.datetime(2013, 2, 6, 4, 54, 49), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 9, 20, 17, 8, 44), 2, 'ce137868-7144-11e5-ba71-058fbc01cf0b', 'Dixon', 'CA', '95620', 'US', '-8'),
 (3, datetime.datetime(2013, 2, 6, 5, 20, 15), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, None, 2, 'ce137912-7144-11e5-ba71-058fbc01cf0b', 'Altadena', 'CA', '91001', 'US', '-8'),
 (3, datetime.datetime(2013, 2, 6, 5, 27, 59), datetime.datetime(2015, 7, 31, 3, 43, 30), 1, 1, 0, None, None, datetime.datetime(2015, 7, 31, 3, 43, 30), 1, 'ce1379c6-7144-11e5-ba71-058fbc01cf0b', 'Los Angeles', 'CA', '90045', 'US', '-8'),
 (12, datetime.datetime(2013, 2, 6, 6, 4, 46), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 0, None, None, datetime.datetime(2014, 5, 24, 20, 29, 34), 2, 'ce137a7a-7144-11e5-ba71-058fbc01cf0b', 'Rosenau', 'A', '68128', 'FR', '-'),
 (12, datetime.datetime(2013, 2, 6, 6, 4, 46), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 0, None, None, datetime.datetime(2014, 5, 24, 20, 29, 34), 2, 'ce137a7a-7144-11e5-ba71-058fbc01cf0b', 'Rosenau', 'A', '68128', 'FR', '-'),
 (25, datetime.datetime(2013, 2, 5, 23, 35, 11), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 4, 2, 15, 53, 11), 2, 'ce137034-7144-11e5-ba71-058fbc01cf0b', 'Sierra Vista', 'AZ', '85635', 'US', '-7'),
 (25, datetime.datetime(2013, 2, 5, 23, 35, 11), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 4, 2, 15, 53, 11), 2, 'ce137034-7144-11e5-ba71-058fbc01cf0b', 'Sierra Vista', 'AZ', '85635', 'US', '-7'),
 (15, datetime.datetime(2013, 2, 6, 14, 13, 42), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, None, 2, 'ce137c78-7144-11e5-ba71-058fbc01cf0b', 'Durham', 'NC', '27713', 'US', '-5'),
 (11, datetime.datetime(2013, 2, 5, 17, 22, 41), datetime.datetime(2015, 7, 1, 21, 43, 37), 2, 2, 1, None, None, datetime.datetime(2015, 7, 1, 21, 43, 37), 2, 'ce135bd0-7144-11e5-ba71-058fbc01cf0b', 'Northbrook', 'IL', '60062', 'US', '-6'),
 (1, datetime.datetime(2013, 2, 6, 16, 55, 7), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, None, 2, 'ce13807e-7144-11e5-ba71-058fbc01cf0b', 'Cincinnati', 'CO', '80304', 'US', '-7'),
 (3, datetime.datetime(2013, 2, 6, 17, 32, 31), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, None, 2, 'ce1381c8-7144-11e5-ba71-058fbc01cf0b', 'Charlotte', 'WA', '98052', 'US', '-8'),
 (2, datetime.datetime(2013, 2, 6, 17, 35, 41), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, datetime.datetime(2014, 10, 13, 12, 3, 41), 2, 'ce138268-7144-11e5-ba71-058fbc01cf0b', 'Boston', 'NJ', '7065', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 6, 17, 44, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce138312-7144-11e5-ba71-058fbc01cf0b', 'Boston', 'AE', '9128', 'US', '-'),
 (6, datetime.datetime(2013, 2, 5, 13, 57, 30), datetime.datetime(2015, 1, 28, 20, 51, 49), 2, 2, 1, None, None, None, 2, 'ce135194-7144-11e5-ba71-058fbc01cf0b', 'Birdsboro', 'PA', '19508', 'US', '-5'),
 (6, datetime.datetime(2013, 2, 5, 13, 57, 30), datetime.datetime(2015, 1, 28, 20, 51, 49), 2, 2, 1, None, None, None, 2, 'ce135194-7144-11e5-ba71-058fbc01cf0b', 'Birdsboro', 'PA', '19508', 'US', '-5'),
 (27, datetime.datetime(2013, 2, 6, 18, 31, 2), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 10, 9, 19, 44, 7), 2, 'ce13851a-7144-11e5-ba71-058fbc01cf0b', 'Rødekro', '83', '6230', 'DK', '-'),
 (27, datetime.datetime(2013, 2, 6, 18, 31, 2), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 10, 9, 19, 44, 7), 2, 'ce13851a-7144-11e5-ba71-058fbc01cf0b', 'Rødekro', '83', '6230', 'DK', '-'),
 (27, datetime.datetime(2013, 2, 6, 18, 41, 57), datetime.datetime(2015, 9, 28, 17, 13, 21), 2, 2, 1, None, None, datetime.datetime(2015, 9, 28, 17, 13, 21), 2, 'ce1385c4-7144-11e5-ba71-058fbc01cf0b', 'Alexandria', 'CA', '94952', 'US', '-8'),
 (27, datetime.datetime(2013, 2, 6, 18, 41, 57), datetime.datetime(2015, 9, 28, 17, 13, 21), 2, 2, 1, None, None, datetime.datetime(2015, 9, 28, 17, 13, 21), 2, 'ce1385c4-7144-11e5-ba71-058fbc01cf0b', 'Alexandria', 'CA', '94952', 'US', '-8'),
 (181, datetime.datetime(2013, 2, 5, 17, 54, 42), datetime.datetime(2015, 1, 28, 20, 51, 49), 13, 2, 1, 1, 0, None, 2, 'ce135e14-7144-11e5-ba71-058fbc01cf0b', 'Raleigh', 'NC', '27606', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 6, 19, 50, 16), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, None, 2, 'ce138722-7144-11e5-ba71-058fbc01cf0b', 'Charlotte', 'NC', '27371', 'US', '-5'),
 (181, datetime.datetime(2013, 2, 5, 17, 54, 42), datetime.datetime(2015, 1, 28, 20, 51, 49), 13, 2, 1, 1, 0, None, 2, 'ce135e14-7144-11e5-ba71-058fbc01cf0b', 'Raleigh', 'NC', '27606', 'US', '-5'),
 (7, datetime.datetime(2013, 2, 6, 22, 19, 24), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce1389d4-7144-11e5-ba71-058fbc01cf0b', 'Woodinville', 'CA', '92116', 'US', '-8'),
 (11, datetime.datetime(2013, 2, 6, 20, 38, 13), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, datetime.datetime(2014, 12, 11, 22, 12, 14), 2, 'ce1387cc-7144-11e5-ba71-058fbc01cf0b', 'Woodinville', 'WA', '98225', 'US', '-8'),
 (4, datetime.datetime(2013, 2, 7, 0, 18, 37), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, datetime.datetime(2015, 1, 1, 17, 46, 36), 1, 'ce138a88-7144-11e5-ba71-058fbc01cf0b', 'Oakland', 'IL', '60626', 'US', '-6'),
 (3, datetime.datetime(2013, 2, 7, 1, 58, 21), datetime.datetime(2015, 6, 22, 8, 8, 59), 2, 1, 1, None, None, datetime.datetime(2015, 6, 22, 8, 8, 59), 1, 'ce138f92-7144-11e5-ba71-058fbc01cf0b', 'Singapore', '1', '249081', 'SG', '#N/A'),
 (3, datetime.datetime(2013, 2, 7, 1, 58, 21), datetime.datetime(2015, 6, 22, 8, 8, 59), 2, 1, 1, None, None, datetime.datetime(2015, 6, 22, 8, 8, 59), 1, 'ce138f92-7144-11e5-ba71-058fbc01cf0b', 'Singapore', '1', '249081', 'SG', '#N/A'),
 (1, datetime.datetime(2013, 2, 7, 2, 15, 49), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce1390f0-7144-11e5-ba71-058fbc01cf0b', 'Oakland', 'DC', '20002', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 7, 4, 19, 57), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 1, 0, None, None, datetime.datetime(2014, 6, 23, 20, 42, 36), 1, 'ce13919a-7144-11e5-ba71-058fbc01cf0b', 'Oakland', 'NY', '11730', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 6, 1, 54, 46), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce137458-7144-11e5-ba71-058fbc01cf0b', 'Durham', 'NC', '27707', 'US', '-5'),
 (6, datetime.datetime(2013, 2, 7, 13, 47, 11), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, datetime.datetime(2014, 4, 2, 16, 44, 1), 2, 'ce1394f6-7144-11e5-ba71-058fbc01cf0b', 'Test', 'OH', '45220', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 7, 13, 51, 21), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce13964a-7144-11e5-ba71-058fbc01cf0b', 'Test', 'FL', '32934', 'US', '-5'),
 (1, datetime.datetime(2013, 2, 7, 14, 24, 47), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce13985c-7144-11e5-ba71-058fbc01cf0b', 'Test', 'FL', '33764', 'US', '-5'),
 (12, datetime.datetime(2013, 2, 6, 2, 46, 55), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce137656-7144-11e5-ba71-058fbc01cf0b', 'Oreland', 'PA', '19075', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 7, 15, 14, 44), datetime.datetime(2015, 1, 29, 19, 13, 14), 1, 2, 1, None, None, datetime.datetime(2015, 1, 29, 19, 13, 14), 2, 'ce139a6e-7144-11e5-ba71-058fbc01cf0b', 'Carrboro', 'PA', '15216', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 7, 15, 22, 22), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 0, None, None, None, 2, 'ce139bea-7144-11e5-ba71-058fbc01cf0b', 'Carrboro', 'TX', '78738', 'US', '-6'),
 (2, datetime.datetime(2013, 2, 7, 15, 22, 22), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 0, None, None, None, 2, 'ce139bea-7144-11e5-ba71-058fbc01cf0b', 'Carrboro', 'TX', '78738', 'US', '-6'),
 (355, datetime.datetime(2013, 2, 5, 17, 17, 31), datetime.datetime(2015, 5, 13, 14, 44, 22), 7, 2, 1, 0, 0, datetime.datetime(2015, 5, 13, 14, 44, 22), 2, 'ce135766-7144-11e5-ba71-058fbc01cf0b', 'Cary', 'NC', '27519', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 7, 15, 22, 6), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce139cb2-7144-11e5-ba71-058fbc01cf0b', 'Carrboro', 'NC', '28412', 'US', '-5'),
 (7, datetime.datetime(2013, 2, 7, 16, 2, 14), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce139e1a-7144-11e5-ba71-058fbc01cf0b', 'Melbourne', 'NM', '87540', 'US', '-7'),
 (5, datetime.datetime(2013, 2, 7, 16, 26, 55), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, None, 2, 'ce13a108-7144-11e5-ba71-058fbc01cf0b', 'Alexandria', 'KS', '66085', 'US', '-6'),
 (12, datetime.datetime(2013, 2, 7, 16, 30, 9), datetime.datetime(2015, 1, 28, 20, 51, 50), 3, 3, 1, None, None, None, 3, 'ce13a5cc-7144-11e5-ba71-058fbc01cf0b', 'Alexandria', 'NY', '14610', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 7, 17, 6, 49), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 1, 1, None, None, None, 1, 'ce13a734-7144-11e5-ba71-058fbc01cf0b', 'Singapore', 'CA', '91301', 'US', '-8'),
 (4, datetime.datetime(2013, 2, 7, 17, 6, 49), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 1, 1, None, None, None, 1, 'ce13a734-7144-11e5-ba71-058fbc01cf0b', 'Singapore', 'CA', '91301', 'US', '-8'),
 (4, datetime.datetime(2013, 2, 7, 17, 28, 44), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, datetime.datetime(2014, 5, 26, 20, 11, 23), 1, 'ce13a7e8-7144-11e5-ba71-058fbc01cf0b', 'Mountain View', 'MA', '1890', 'US', '-5'),
 (181, datetime.datetime(2013, 2, 5, 17, 54, 42), datetime.datetime(2015, 1, 28, 20, 51, 49), 13, 2, 1, 1, 0, None, 2, 'ce135e14-7144-11e5-ba71-058fbc01cf0b', 'Raleigh', 'NC', '27606', 'US', '-5'),
 (8, datetime.datetime(2013, 2, 7, 19, 26, 41), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce13b152-7144-11e5-ba71-058fbc01cf0b', 'Mountain View', 'OR', '97501', 'US', '-8'),
 (7, datetime.datetime(2013, 2, 7, 19, 33, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 3, 1, None, None, None, 3, 'ce21d7d2-7144-11e5-ba71-058fbc01cf0b', 'Bloomfield Hills', 'MO', '64119', 'US', '-6'),
 (7, datetime.datetime(2013, 2, 7, 19, 33, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 3, 1, None, None, None, 3, 'ce21d7d2-7144-11e5-ba71-058fbc01cf0b', 'Bloomfield Hills', 'MO', '64119', 'US', '-6'),
 (41, datetime.datetime(2013, 2, 6, 16, 42, 56), datetime.datetime(2015, 7, 1, 14, 21, 38), 3, 2, 1, None, None, datetime.datetime(2015, 7, 1, 14, 21, 38), 2, 'ce137fca-7144-11e5-ba71-058fbc01cf0b', 'Owings', 'MD', '20736', 'US', '-5'),
 (24, datetime.datetime(2013, 2, 7, 21, 8, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 3, 2, 1, None, None, datetime.datetime(2014, 11, 2, 13, 48, 32), 2, 'ce21df2a-7144-11e5-ba71-058fbc01cf0b', 'Bloomfield Hills', 'FL', '33881', 'US', '-5'),
 (23, datetime.datetime(2013, 2, 7, 21, 8, 53), datetime.datetime(2015, 5, 20, 16, 13, 32), 2, 2, 1, None, None, datetime.datetime(2015, 5, 20, 16, 13, 32), 2, 'ce21e11e-7144-11e5-ba71-058fbc01cf0b', 'Philadelphia', 'CT', '6234', 'US', '-5'),
 (24, datetime.datetime(2013, 2, 7, 21, 8, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 3, 2, 1, None, None, datetime.datetime(2014, 11, 2, 13, 48, 32), 2, 'ce21df2a-7144-11e5-ba71-058fbc01cf0b', 'Bloomfield Hills', 'FL', '33881', 'US', '-5'),
 (23, datetime.datetime(2013, 2, 7, 21, 8, 53), datetime.datetime(2015, 5, 20, 16, 13, 32), 2, 2, 1, None, None, datetime.datetime(2015, 5, 20, 16, 13, 32), 2, 'ce21e11e-7144-11e5-ba71-058fbc01cf0b', 'Philadelphia', 'CT', '6234', 'US', '-5'),
 (24, datetime.datetime(2013, 2, 7, 21, 8, 3), datetime.datetime(2015, 1, 28, 20, 51, 50), 3, 2, 1, None, None, datetime.datetime(2014, 11, 2, 13, 48, 32), 2, 'ce21df2a-7144-11e5-ba71-058fbc01cf0b', 'Bloomfield Hills', 'FL', '33881', 'US', '-5'),
 (2, datetime.datetime(2013, 2, 7, 22, 16, 32), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 0, None, None, None, 1, 'ce21e736-7144-11e5-ba71-058fbc01cf0b', 'Durham', 'NY', '10065', 'US', '-5'),
 (7, datetime.datetime(2013, 2, 7, 23, 12, 58), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce21e826-7144-11e5-ba71-058fbc01cf0b', 'Test', 'NJ', '7035', 'US', '-5'),
 (8, datetime.datetime(2013, 2, 8, 0, 16, 38), datetime.datetime(2015, 1, 28, 20, 51, 50), 2, 2, 1, None, None, datetime.datetime(2014, 11, 26, 17, 31, 56), 2, 'ce21f122-7144-11e5-ba71-058fbc01cf0b', 'Test', 'IL', '60614', 'US', '-6'),
 (5, datetime.datetime(2013, 2, 8, 0, 25, 59), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, datetime.datetime(2014, 7, 19, 0, 2, 51), 2, 'ce21f528-7144-11e5-ba71-058fbc01cf0b', 'Davis', 'GA', '30092', 'US', '-5'),
 (7, datetime.datetime(2013, 2, 8, 1, 0, 16), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 1, 1, None, None, None, 1, 'ce22007c-7144-11e5-ba71-058fbc01cf0b', 'Davis', 'FL', '32205', 'US', '-5'),
 (17, datetime.datetime(2013, 2, 8, 1, 5, 28), datetime.datetime(2015, 8, 29, 2, 16, 30), 3, 1, 1, None, None, datetime.datetime(2015, 8, 29, 2, 16, 30), 1, 'ce22011c-7144-11e5-ba71-058fbc01cf0b', 'Davis', 'TX', '77386', 'US', '-6'),
 (17, datetime.datetime(2013, 2, 8, 1, 5, 28), datetime.datetime(2015, 8, 29, 2, 16, 30), 3, 1, 1, None, None, datetime.datetime(2015, 8, 29, 2, 16, 30), 1, 'ce22011c-7144-11e5-ba71-058fbc01cf0b', 'Davis', 'TX', '77386', 'US', '-6'),
 (46, datetime.datetime(2013, 2, 8, 2, 33, 36), datetime.datetime(2015, 9, 20, 23, 4, 2), 3, 2, 1, None, None, datetime.datetime(2015, 9, 20, 23, 4, 2), 2, 'ce2202e8-7144-11e5-ba71-058fbc01cf0b', 'Goshen', 'OH', '45122', 'US', '-5'),
 (46, datetime.datetime(2013, 2, 8, 2, 33, 36), datetime.datetime(2015, 9, 20, 23, 4, 2), 3, 2, 1, None, None, datetime.datetime(2015, 9, 20, 23, 4, 2), 2, 'ce2202e8-7144-11e5-ba71-058fbc01cf0b', 'Goshen', 'OH', '45122', 'US', '-5'),
 (91, datetime.datetime(2013, 2, 8, 2, 49, 7), datetime.datetime(2015, 5, 18, 2, 51, 44), 1, 2, 1, None, None, datetime.datetime(2015, 5, 18, 2, 51, 44), 2, 'ce2203f6-7144-11e5-ba71-058fbc01cf0b', 'Spokane', 'WA', '99208', 'US', '-8'),
 (28, datetime.datetime(2013, 2, 8, 3, 6, 42), datetime.datetime(2015, 5, 27, 20, 41, 44), 2, 2, 1, None, None, datetime.datetime(2015, 5, 27, 20, 41, 44), 2, 'ce2204a0-7144-11e5-ba71-058fbc01cf0b', 'Saint Louis', 'MO', '63109', 'US', '-6'),
 (28, datetime.datetime(2013, 2, 8, 3, 6, 42), datetime.datetime(2015, 5, 27, 20, 41, 44), 2, 2, 1, None, None, datetime.datetime(2015, 5, 27, 20, 41, 44), 2, 'ce2204a0-7144-11e5-ba71-058fbc01cf0b', 'Saint Louis', 'MO', '63109', 'US', '-6'),
 (3, datetime.datetime(2013, 2, 8, 3, 37, 49), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 1, None, None, datetime.datetime(2014, 3, 15, 16, 3, 53), 1, 'ce220734-7144-11e5-ba71-058fbc01cf0b', 'Washington', 'DC', '20003', 'US', '-5'),
 (7, datetime.datetime(2013, 2, 8, 3, 35, 59), datetime.datetime(2015, 5, 4, 12, 51, 28), 2, 2, 1, None, None, datetime.datetime(2015, 5, 4, 12, 51, 28), 2, 'ce2205ea-7144-11e5-ba71-058fbc01cf0b', 'Denham Springs', 'LA', '70726', 'US', '-6'),
 (7, datetime.datetime(2013, 2, 8, 3, 35, 59), datetime.datetime(2015, 5, 4, 12, 51, 28), 2, 2, 1, None, None, datetime.datetime(2015, 5, 4, 12, 51, 28), 2, 'ce2205ea-7144-11e5-ba71-058fbc01cf0b', 'Denham Springs', 'LA', '70726', 'US', '-6'),
 (5, datetime.datetime(2013, 2, 8, 3, 48, 24), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 0, None, None, None, 1, 'ce2207de-7144-11e5-ba71-058fbc01cf0b', 'Everett', 'WA', '98201', 'US', '-8'),
 (4, datetime.datetime(2013, 2, 8, 4, 30, 14), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 0, None, None, datetime.datetime(2014, 6, 9, 0, 11, 54), 1, 'ce220892-7144-11e5-ba71-058fbc01cf0b', 'Henderson', 'NV', '89011', 'US', '-8'),
 (5, datetime.datetime(2013, 2, 8, 14, 20, 45), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 1, None, None, None, 1, 'ce220a72-7144-11e5-ba71-058fbc01cf0b', 'London ', 'LND', 'N4 4EU', 'GB', '#N/A'),
 (6, datetime.datetime(2013, 2, 8, 14, 34, 58), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 1, None, None, None, 1, 'ce220b12-7144-11e5-ba71-058fbc01cf0b', 'Hancock', 'NH', '3449', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 8, 15, 20, 50), datetime.datetime(2015, 1, 28, 20, 51, 51), 2, 2, 1, None, None, None, 2, 'ce220bb2-7144-11e5-ba71-058fbc01cf0b', 'Old Lyme', 'CT', '6371', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 8, 15, 20, 50), datetime.datetime(2015, 1, 28, 20, 51, 51), 2, 2, 1, None, None, None, 2, 'ce220bb2-7144-11e5-ba71-058fbc01cf0b', 'Old Lyme', 'CT', '6371', 'US', '-5'),
 (16, datetime.datetime(2013, 2, 8, 17, 53, 17), datetime.datetime(2015, 10, 6, 17, 1, 53), 1, 1, 0, None, None, datetime.datetime(2015, 10, 6, 17, 1, 53), 1, 'ce220cf2-7144-11e5-ba71-058fbc01cf0b', 'Duncanville', 'TX', '75116', 'US', '-6'),
 (14, datetime.datetime(2013, 2, 8, 4, 59, 58), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 0, None, None, None, 1, 'ce2209d2-7144-11e5-ba71-058fbc01cf0b', 'Victoria', 'BC', 'V8P', 'CA', '#N/A'),
 (14, datetime.datetime(2013, 2, 8, 4, 59, 58), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 0, None, None, None, 1, 'ce2209d2-7144-11e5-ba71-058fbc01cf0b', 'Victoria', 'BC', 'V8P', 'CA', '#N/A'),
 (1, datetime.datetime(2013, 2, 8, 18, 30, 56), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 1, 1, None, None, None, 1, 'ce220e3c-7144-11e5-ba71-058fbc01cf0b', 'Portland', 'OR', '97211', 'US', '-8'),
 (2, datetime.datetime(2013, 2, 8, 18, 36, 35), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 2, 0, None, None, None, 2, 'ce220ee6-7144-11e5-ba71-058fbc01cf0b', 'Southington', 'CT', '6489', 'US', '-5'),
 (4, datetime.datetime(2013, 2, 6, 16, 17, 57), datetime.datetime(2015, 1, 28, 20, 51, 50), 1, 2, 1, None, None, datetime.datetime(2014, 2, 9, 0, 29, 51), 2, 'ce137e80-7144-11e5-ba71-058fbc01cf0b', 'Kapolei', 'HI', '96707', 'US', '-10'),
 (6, datetime.datetime(2013, 2, 8, 20, 51, 1), datetime.datetime(2015, 1, 28, 20, 51, 51), 2, 2, 1, None, None, None, 2, 'ce221210-7144-11e5-ba71-058fbc01cf0b', 'Suffield', 'CT', '6078', 'US', '-5'),
 (6, datetime.datetime(2013, 2, 8, 20, 51, 1), datetime.datetime(2015, 1, 28, 20, 51, 51), 2, 2, 1, None, None, None, 2, 'ce221210-7144-11e5-ba71-058fbc01cf0b', 'Suffield', 'CT', '6078', 'US', '-5'),
 (3, datetime.datetime(2013, 2, 8, 21, 36, 50), datetime.datetime(2015, 1, 28, 20, 51, 51), 1, 2, 1, None, None, None, 2, 'ce22135a-7144-11e5-ba71-058fbc01cf0b', 'Atlanta', 'GA', '30345', 'US', '-5'),
 (310, datetime.datetime(2013, 2, 5, 0, 45, 15), datetime.datetime(2015, 2, 23, 13, 39, 48), 3, 2, 1, 1, 0, datetime.datetime(2015, 2, 23, 13, 39, 48), 2, 'ce134a78-7144-11e5-ba71-058fbc01cf0b', 'Durham', 'NC', '27701', 'US', '-5'),

## You have already learned how to see all the data in your database!  Congratulations!  

Feel free to practice any other queries you are interested in below: